[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[env]
NODE_ENV = "production"
PORT = "3001"
HOST = "0.0.0.0"