[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[[services]]
name = "mcp-server"

[services.build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[services.deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

[[services.variables]]
name = "NODE_ENV"
value = "production"

[[services.variables]]
name = "PORT"
value = "3001"

[[services.variables]]
name = "HOST"  
value = "0.0.0.0"